### ISSUE TITLE
Usage of GradientSetup.UseEnvironment

### ISSUE THREAD

**Issue by Nucs** [losttech/Gradient#7]
Can you provide an example of what paths to place in `GradientSetup.UseEnvironment(...)`.

**Comment by lostmsu** [comment]
@Nucs, please take a look at https://github.com/losttech/WhichPython/blob/master/src/PythonEnvironment.cs (it is a dependency of Gradient).

You can use `PythonEnvironment.EnumerateEnvironments` to get the list of Python environments Gradient will recognize automatically on your machine.

These environments will also give you an idea of what to pass to the `PythonEnvironment` constructor, if you want a custom one.

**Comment by Nucs** [comment]
EnumerateEnvironments returns an empty enumerate.
I'm opening an issue there explaining the problem.

**Comment by Nucs** [comment]
Incase anyone needs to know how a loaded environment looks like:
![image](https://user-images.githubusercontent.com/649919/59426424-d65b2900-8de0-11e9-8d2c-f32ab1a4f99b.png)

**Comment by lostmsu** [comment]
Just FYI, this is just for Windows. On Linux and MacOS it will look differently.
